language: go
go: 
 - 1.1
 - 1.2
 - 1.3
 - release
 - tip

install:
 - go get github.com/zhangpeihao/goflv
 - go get github.com/zhangpeihao/goamf
 - go get github.com/zhangpeihao/log

script:
 - go test -v ./...
